// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
//
// ===========================================================

`timescale 1 ns / 1 ps

(* CORE_GENERATION_INFO="Lookup_0_Lookup_0,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvm1802-vsvd1760-2MP-e-S,HLS_INPUT_CLOCK=2.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.460000,HLS_SYN_LAT=45,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=770,HLS_SYN_LUT=1000,HLS_VERSION=2021_2}" *)

module Lookup_0 (
        ap_local_block,
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        in0_V_TDATA,
        in0_V_TVALID,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        out_V_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

output   ap_local_block;
input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] in0_V_TDATA;
input   in0_V_TVALID;
output   in0_V_TREADY;
output  [31:0] out_V_TDATA;
output   out_V_TVALID;
input   out_V_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

wire   [0:0] ap_local_deadlock;
 reg    ap_rst_n_inv;
wire   [63:0] mem;
reg    gmem_blk_n_AR;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
reg    in0_V_TDATA_blk_n;
wire    ap_CS_fsm_state2;
reg   [63:0] mem_read_reg_143;
wire    ap_CS_fsm_state1;
reg   [61:0] trunc_ln_reg_151;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_start;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_done;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_idle;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_ready;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWVALID;
wire   [63:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWADDR;
wire   [0:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWID;
wire   [31:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWLEN;
wire   [2:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWSIZE;
wire   [1:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWBURST;
wire   [1:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWLOCK;
wire   [3:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWCACHE;
wire   [2:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWPROT;
wire   [3:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWQOS;
wire   [3:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWREGION;
wire   [0:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWUSER;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WVALID;
wire   [31:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WDATA;
wire   [3:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WSTRB;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WLAST;
wire   [0:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WID;
wire   [0:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WUSER;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARVALID;
wire   [63:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARADDR;
wire   [0:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARID;
wire   [31:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARLEN;
wire   [2:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARSIZE;
wire   [1:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARBURST;
wire   [1:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARLOCK;
wire   [3:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARCACHE;
wire   [2:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARPROT;
wire   [3:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARQOS;
wire   [3:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARREGION;
wire   [0:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARUSER;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_RREADY;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_BREADY;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_out_V_TREADY;
wire   [31:0] grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_out_V_TDATA;
wire    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_out_V_TVALID;
wire    gmem_AWREADY;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [0:0] gmem_ARID;
reg   [31:0] gmem_ARLEN;
reg   [2:0] gmem_ARSIZE;
reg   [1:0] gmem_ARBURST;
reg   [1:0] gmem_ARLOCK;
reg   [3:0] gmem_ARCACHE;
reg   [2:0] gmem_ARPROT;
reg   [3:0] gmem_ARQOS;
reg   [3:0] gmem_ARREGION;
reg   [0:0] gmem_ARUSER;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [8:0] gmem_RFIFONUM;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg    grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire  signed [63:0] sext_ln28_fu_133_p1;
wire   [0:0] tmp_nbreadreq_fu_76_p3;
wire   [40:0] shl_ln_fu_106_p3;
wire   [63:0] zext_ln28_fu_114_p1;
wire   [63:0] add_ln28_fu_118_p2;
reg   [11:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    regslice_both_out_V_U_apdone_blk;
wire    ap_CS_fsm_state12;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [31:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_start_reg = 1'b0;
end

Lookup_0_Lookup_0_Pipeline_VITIS_LOOP_28_1 grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_start),
    .ap_done(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_done),
    .ap_idle(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_idle),
    .ap_ready(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_ready),
    .m_axi_gmem_AWVALID(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .out_V_TREADY(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_out_V_TREADY),
    .sext_ln28(trunc_ln_reg_151),
    .out_V_TDATA(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_out_V_TDATA),
    .out_V_TVALID(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_out_V_TVALID)
);

Lookup_0_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mem(mem),
    .ap_local_deadlock(ap_local_deadlock)
);

Lookup_0_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARID(gmem_ARID),
    .I_ARLEN(gmem_ARLEN),
    .I_ARSIZE(gmem_ARSIZE),
    .I_ARLOCK(gmem_ARLOCK),
    .I_ARCACHE(gmem_ARCACHE),
    .I_ARQOS(gmem_ARQOS),
    .I_ARPROT(gmem_ARPROT),
    .I_ARUSER(gmem_ARUSER),
    .I_ARBURST(gmem_ARBURST),
    .I_ARREGION(gmem_ARREGION),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

Lookup_0_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

Lookup_0_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_out_V_TDATA),
    .vld_in(grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_out_V_TVALID),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_start_reg <= 1'b1;
        end else if ((grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_ready == 1'b1)) begin
            grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        mem_read_reg_143 <= mem;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln_reg_151 <= {{add_ln28_fu_118_p2[63:2]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((in0_V_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARADDR = sext_ln28_fu_133_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARADDR = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARBURST = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARBURST;
    end else begin
        gmem_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARCACHE = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARCACHE;
    end else begin
        gmem_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARID = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARID;
    end else begin
        gmem_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARLEN = 32'd75;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLEN = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLOCK = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARLOCK;
    end else begin
        gmem_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARPROT = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARPROT;
    end else begin
        gmem_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARQOS = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARQOS;
    end else begin
        gmem_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARREGION = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARREGION;
    end else begin
        gmem_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARSIZE = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARSIZE;
    end else begin
        gmem_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARUSER = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARUSER;
    end else begin
        gmem_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARVALID = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_RREADY = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (in0_V_TVALID_int_regslice == 1'b1))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_76_p3 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (in0_V_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (gmem_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (regslice_both_out_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln28_fu_118_p2 = (zext_ln28_fu_114_p1 + mem_read_reg_143);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'd0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_start = grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_ap_start_reg;

assign grp_Lookup_0_Pipeline_VITIS_LOOP_28_1_fu_97_out_V_TREADY = (out_V_TREADY_int_regslice & ap_CS_fsm_state11);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign sext_ln28_fu_133_p1 = $signed(trunc_ln_reg_151);

assign shl_ln_fu_106_p3 = {{in0_V_TDATA_int_regslice}, {9'd0}};

assign tmp_nbreadreq_fu_76_p3 = in0_V_TVALID_int_regslice;

assign zext_ln28_fu_114_p1 = shl_ln_fu_106_p3;

endmodule //Lookup_0
